import {
  Box,
  Button,
  Heading,
  VStack,
  HStack,
  useColorMode,
  useColorModeValue,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/Footer";

const Home: NextPage = () => {
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <>
      <Head>
        <title>HKerStanley Homepage</title>
        <meta
          name="description"
          content="HKerStanley's Homepage generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box width="100vw">
        <VStack justifyContent={"space-between"}>
          <HStack>
            <Heading>stanchy.eth</Heading>
            <Button onClick={toggleColorMode}>
              Toggle {colorMode === "light" ? "Dark" : "Light"}
            </Button>
          </HStack>
          <Box>
            <Heading>Hi I am HKerStanley</Heading>
          </Box>
          <Footer />
        </VStack>
      </Box>
    </>
  );
};

export default Home;
