import {
  Box,
  Button,
  ColorModeScript,
  Heading,
  LightMode,
  useColorMode,
  useColorModeValue,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";

const Home: NextPage = () => {
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <>
      <Head>
        <title>HKerStanley's Homepage</title>
        <meta
          name="description"
          content="HKerStanley's Homepage generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>
        <Button onClick={toggleColorMode}>
          Toggle {colorMode === "light" ? "Dark" : "Light"}
        </Button>
        <Heading>Hi I am HKerStanley</Heading>
      </Box>
      <Footer />
    </>
  );
};

export default Home;
